# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 19:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('net_income', models.IntegerField(default=0)),
                ('total_assets', models.IntegerField(default=0)),
                ('total_liability', models.IntegerField(default=0)),
                ('return_on_equity', models.DecimalField(max_digits=5, decimal_places=4)),
                ('total_num_loans_small', models.IntegerField(default=0)),
                ('total_num_loans_micro', models.IntegerField(default=0)),
                ('total_num_loans_farm', models.IntegerField(default=0)),
                ('total_loans', models.IntegerField(default=0)),
                ('total_amount_individual', models.IntegerField(default=0)),
                ('total_amount_small', models.IntegerField(default=0)),
                ('total_amount_micro', models.IntegerField(default=0)),
                ('total_amount_farm', models.IntegerField(default=0)),
                ('individual_loan_percentage', models.FloatField()),
                ('small_loan_percentage', models.FloatField()),
                ('micro_loan_percentage', models.FloatField()),
                ('farm_loan_percentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='bank',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lending_app.State'),
        ),
    ]
